# Generated by Django 3.1.2 on 2022-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
