# Generated by Django 3.1.2 on 2022-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_cantidad',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
