# Generated by Django 3.1.2 on 2022-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_producto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_nombre', models.CharField(max_length=50)),
                ('contacto_correo', models.EmailField(max_length=254)),
                ('contacto_tipo', models.ImageField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'suguerencia'], [3, 'felicitaciones']], upload_to='')),
                ('contacto_mensaje', models.TextField()),
                ('contacto_avisos', models.BooleanField()),
            ],
        ),
    ]
