# Generated by Django 3.1.2 on 2022-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='contacto_tipo',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'suguerencia'], [3, 'felicitaciones']]),
        ),
    ]
