# Generated by Django 4.1.3 on 2022-11-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221113_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=50)),
                ('categoria_imagen', models.ImageField(null=True, upload_to='categorias')),
            ],
        ),
    ]
