# Generated by Django 4.1.3 on 2022-11-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
        ),
    ]
